---
name: Deployment

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    permissions:
      contents: read
      pages: write
      id-token: write
    strategy:
      max-parallel: 4
      matrix:
        go-version: [1.25.x]
        node-version: ["24"]
        hugo-version: ["0.152.2"]

    steps:
      - uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
        with:
          egress-policy: audit

      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0

      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version: "${{ matrix.go-version }}"

      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/configure-pages@v5
        id: pages

      - run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${{ matrix.hugo-version }}/hugo_extended_${{ matrix.hugo-version }}_linux-amd64.deb
          sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - run: |
          sudo snap install dart-sass

      - run: |
          echo "Dart Sass: $(sass --version)"
          echo "Go: $(go version)"
          echo "Hugo: $(hugo version)"
          echo "Node.js: $(node --version)"

      - run: |
          [[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true

      - run: |
          hugo \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/" \
            --cacheDir "${{ runner.temp }}/hugo_cache"

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deployment:
    runs-on: ubuntu-latest
    name: Deployment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs:
      - build

    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
