---
name: Verify

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  conform:
    runs-on: ubuntu-latest
    name: Conform

    steps:
      - uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
        with:
          egress-policy: audit

      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0

      - uses: siderolabs/conform@6380738b7fdfc68b208ce0674c4ac1ba314ba600 # v0.1.0-alpha.27
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  lint:
    runs-on: ubuntu-latest
    name: Lint
    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
        with:
          egress-policy: audit

      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0

      - uses: super-linter/super-linter/slim@502f4fe48a81a392756e173e39a861f8c8efe056 # v8.3.0
        env:
          LINTER_RULES_PATH: .
          VALIDATE_MARKDOWN: true
          MARKDOWN_CONFIG_FILE: .markdownlint.yaml
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    name: Build
    strategy:
      max-parallel: 4
      matrix:
        go-version: [1.25.x]
        node-version: ["24"]
        hugo-version: ["0.152.2"]

    steps:
      - uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
        with:
          egress-policy: audit

      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0

      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version: "${{ matrix.go-version }}"

      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5
        id: pages

      - run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${{ matrix.hugo-version }}/hugo_extended_${{ matrix.hugo-version }}_linux-amd64.deb
          sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - run: |
          sudo snap install dart-sass

      - run: |
          echo "Dart Sass: $(sass --version)"
          echo "Go: $(go version)"
          echo "Hugo: $(hugo version)"
          echo "Node.js: $(node --version)"

      - run: |
          [[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true

      - run: |
          hugo build
